pangeo:
  jupyterhub:
    scheduling:
      userPlaceholder:
        enabled: true
        replicas: 4
    proxy:
      https:
        enabled: true
        hosts:
        - ooi.pangeo.io
        letsencrypt:
          contactEmail: tjcrone@gmail.com
      service:
        annotations: {'service.beta.kubernetes.io/azure-load-balancer-resource-group': 'ooi-pangeo'}
        loadBalancerIP: 23.96.23.164
