pangeo:
  jupyterhub:
    singleuser:
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            - "sh"
            - "-c"
            - >
              id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan ;
              id && chown 1000:1000 /srv/shared && ls -lhd /srv/shared ;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: home
              mountPath: /home/jovyan
              subPath: "pangeo-csiro.munroelab.ca/home/{username}"
              # Alternatively, ssh into node and chown once
            - name: jupyterhub-shared
              mountPath: /srv/shared
              subPath: "pangeo-csiro.munroelab.ca/shared"
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: data-nfs
      lifecycleHooks:
        # NOTE: requires user-condarc manually be put on efs drive, should automate this
        postStart:
          exec:
            command:
              - "sh"
              - "-c"
              - >
                cp /home/jovyan/shared/user-condarc.txt  /home/jovyan/.condarc ;
                test -d /home/jovyan/shared || ln -sf /srv/shared /home/jovyan/shared ;
      extraEnv:
        #PATH: '{PATH}:/srv/shared/bin' #Not sure how to append to path...
        EXAMPLES_GIT_URL: https://github.com/pangeo-data/pangeo-example-notebooks
      storage:
        type: static
        static:
          pvcName: home-nfs
          subPath: "pangeo-csiro.munroelab.ca/home/{username}"
        #requires having run config/shared--nfs.yaml
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/shared
            subPath: "pangeo-csiro.munroelab.ca/shared"
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: shared-nfs

      cloudMetadata:
        enabled: true
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: user-notebook
      cpu:
        limit: 4
        guarantee: 3
      memory:
        limit: 16G
        guarantee: 14G
      profileList:
        - display_name: "Default environment (m5.2xlarge | 4 cores, 16Gb)"
          description: "CSIRO environment extending pangeo-notebook"
          default: true
        - display_name: "Pangeo-notebook (m5.2xlarge | 4 cores, 16Gb)"
          description: "latest pangeo-notebook from pangeo stacks"
          kubespawner_override:
            image: pangeo/pangeo-notebook:latest
    auth:
      github:
        orgWhitelist:
          - "csiro-dcfp"
      scopes:
        - "read:user"
        - "read:org"
      admin:
        access: true
        users:
          - jmunroe
    proxy:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: hub
    hub:
      resources:
        requests:
          cpu: "0.5"
          memory: 1Gi
        limits:
          cpu: "1.25"
          memory: 1Gi
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: hub
      extraConfig:
        cloneRepo: |
          # Hack solution for branding
          import os, shutil
          repo = 'https://github.com/csiro-dcfp/pangeo-custom-jupyterhub-templates'
          webdir = '/usr/local/share/jupyterhub/static'
          dst = '/srv/jupyterhub/style'
          shutil.rmtree(dst, ignore_errors=True)
          os.system(f'git clone {repo} {dst}')
          os.system(f'cp -rf {dst}/extra-assets {webdir}')
        customPodHook: |
          c.JupyterHub.template_paths = ['/srv/jupyterhub/style/templates']
          c.JupyterHub.template_vars = {
            'pangeo_hub_title': 'pangeo-csiro.munroelab.ca',
            'pangeo_hub_subtitle': 'a community hub for the CSIRO DCFP project',
            'pangeo_welcome': """Welcome to pangeo-csiro.munroelab.ca! This hub lives in AWS region <code>ap-southeast-2</code>. It is maintained and supported by the <a href="https://research.csiro.au/dfp/">CSIRO DCFP project</a> with cloud credits from Amazon. Access is currently limited to the <a href="https://github.com/csiro-dcfp">CSIRO DCFP GitHub Organization</a>. The hub's configuration is stored in this <a href="https://github.com/csiro-dcfp/pangeo-cloud-federation/">github repository</a>. To provide feedback and report any technical problems, please use the <a href="https://github.com/pangeo-data/pangeo-cloud-federation/issues">github issue tracker</a>."""
          }
      extraVolumes:
        - name: custom-assets
          emptyDir: {}
      extraVolumeMounts:
        - name: custom-assets
          mountPath: /usr/local/share/jupyterhub/static/extra-assets


homeDirectories:
  nfs:
    enabled: true
    serverIP: fs-f1f7b0c8.efs.ap-southeast-2.amazonaws.com
