# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - pangeo-csiro.munroelab.ca
        letsencrypt:
          contactEmail: James.Munroe@csiro.au
      service:
        loadBalancerIP: a0e73a1e196c611e9a7340a8937cf3e6-118513723.ap-southeast-2.elb.amazonaws.com
    auth:

      github:
        callbackUrl: "https://pangeo-csiro.munroelab.ca/hub/oauth_callback"
