# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - staging.pangeo-csiro.munroelab.ca
        letsencrypt:
          contactEmail: James.Munroe@csiro.au
      service:
        loadBalancerIP: a17c21a3e96b611e9a7340a8937cf3e6-414565530.ap-southeast-2.elb.amazonaws.com
    auth:
      github:
        callbackUrl: "https://staging.pangeo-csiro.munroelab.ca/hub/oauth_callback"
