# Leave commented for first build, then uncomment and add loadBalancerIP
pangeo:
  jupyterhub:
    proxy:
      https:
        hosts:
        - esip.pangeo.io
        letsencrypt:
          contactEmail: rsignell@usgs.gov
      service:
        loadBalancerIP: ab3a12c8cad8811e98d2e0e9ff0b5f55-1732099509.us-west-2.elb.amazonaws.com
    auth:
      github:
        callbackUrl: "https://esip.pangeo.io/hub/oauth_callback"
